#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-typing
Version  : 3.10.0.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/b0/1b/835d4431805939d2996f8772aca1d2313a57e8860fec0e48e8e7dfe3a477/typing-3.10.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/1b/835d4431805939d2996f8772aca1d2313a57e8860fec0e48e8e7dfe3a477/typing-3.10.0.0.tar.gz
Summary  : Type Hints for Python
Group    : Development/Tools
License  : Python-2.0
Requires: pypi-typing-license = %{version}-%{release}
Requires: pypi-typing-python = %{version}-%{release}
Requires: pypi-typing-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
This is a backport of the standard library typing module to Python
        versions older than 3.5.  (See note below for newer versions.)
        
        Typing defines a standard notation for Python function and variable
        type annotations. The notation can be used for documenting code in a
        concise, standard format, and it has been designed to also be used by
        static and runtime type checkers, static analyzers, IDEs and other
        tools.

%package license
Summary: license components for the pypi-typing package.
Group: Default

%description license
license components for the pypi-typing package.


%package python
Summary: python components for the pypi-typing package.
Group: Default
Requires: pypi-typing-python3 = %{version}-%{release}

%description python
python components for the pypi-typing package.


%package python3
Summary: python3 components for the pypi-typing package.
Group: Default
Requires: python3-core
Provides: pypi(typing)

%description python3
python3 components for the pypi-typing package.


%prep
%setup -q -n typing-3.10.0.0
cd %{_builddir}/typing-3.10.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639060206
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-typing
cp %{_builddir}/typing-3.10.0.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-typing/7ad627868f90ad068bd06801aab97ec1ca34b890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-typing/7ad627868f90ad068bd06801aab97ec1ca34b890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
